---
title: "Color y recompensas"
author: "Marcial"
date: "01/09/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
1. Install and load packages

```{r, echo = F}
#library("devtools")
#devtools::install_github("jinyizju/V.PhyloMaker2")
library(V.PhyloMaker2)

# github (requires `remotes` or `devtools`)
#devtools::install_github("ecoinfor/U.Taxonstand")
library(U.Taxonstand)

```


3. Frequency matrix.

```{r, echo = F}
mydata <- read.csv("./PIGMENT_EVOLUTION_V7.csv") 
dim(mydata)
```



3. Create your tree and plot

```{r, echo = F}

# load the database

library(openxlsx)
#dat1 <- read.xlsx("WFO_v2.1_20230304_part1.xlsx")
#dat2 <- read.xlsx("WFO_v2.1_20230304_part2.xlsx")
#dat3 <- read.xlsx("WFO_v2.1_20230304_part3.xlsx")
dat1 <- read.xlsx("Plants_WP_database_part1.xlsx")
dat2 <- read.xlsx("Plants_WP_database_part2.xlsx")
dat3 <- read.xlsx("Plants_WP_database_part3.xlsx")
database <- rbind(dat1, dat2, dat3)
#We are going to use the WP database but there are many differnt options
#Check here https://github.com/nameMatch/Database/tree/main

rm(dat1, dat2, dat3)

corrected.species <- nameMatch(mydata$Species..names.WFO.2,spSource=database, author = FALSE, max.distance= 1, matchFirst=TRUE)

corrected.species
#make corrections to your database if necessary
names(corrected.species)
write.csv(corrected.species, file = "corrected.species.csv")

c1<- corrected.species$Accepted_SPNAME
c2<- corrected.species$Genus_in_database
c3<- corrected.species$Family
mydata2 <- data.frame(species = c1, genus = c2, family = c3)

mytree <- phylo.maker(sp.list = mydata2, tree = GBOTB.extended.WP, nodes = nodes.info.1.WP, scenarios = "S2")
#There is available S1 and S3 and nodes.info.2.WP.csv

plot(mytree$scenario.2, cex = 0.5)





pdffn = paste0("myphylo", ".scenario2.pdf")
pdf(file=pdffn, width=6, height=60)
plot(mytree$scenario.2, cex = 0.5)
dev.off()
write.tree(mytree$scenario.2, file = "mytree2.tree")



```



Analyses with corHMM
```{r}

library(corHMM)

names(mydata)
mydata <- cbind(mydata,corrected.species$Accepted_SPNAME)
names(mydata)[12]<-"Accepted_SPNAME"
mydata[,12]<- gsub(" ", "_", mydata[,12])


Anthocyanins <- cbind (as.character(mydata[,12][!is.na(mydata[,7])]),mydata[,7][!is.na(mydata[,7])])
library(phytools)
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,Anthocyanins[,1])
tree <- drop.tip(tree, tipstoremove)

pp.Anthocyanins.ARD.2<-corHMM(tree,Anthocyanins,rate.cat=2,node.states="marginal")
pp.Anthocyanins.ARD.2
pp.Anthocyanins.ARD.1<-corHMM(tree,Anthocyanins,rate.cat=1,node.states="marginal")
pp.Anthocyanins.ARD.1
pp.Anthocyanins.ER.2<-corHMM(tree,Anthocyanins,rate.cat=2, model = "ER", node.states="marginal")
pp.Anthocyanins.ER.2
pp.Anthocyanins.ER.1<-corHMM(tree,Anthocyanins,rate.cat=1, model = "ER", node.states="marginal")
pp.Anthocyanins.ER.1
pp.Anthocyanins.ARD.3<-corHMM(tree,Anthocyanins,rate.cat=3, node.states="marginal")
pp.Anthocyanins.ARD.3
pp.Anthocyanins.ER.3<-corHMM(tree,Anthocyanins,rate.cat=3, model = "ER", node.states="marginal")
pp.Anthocyanins.ER.3

simmap.Anthocyanins <- makeSimmap(tree=tree, data=Anthocyanins, model=pp.Anthocyanins.ER.2$solution, rate.cat=2, nSim=100, nCores=1)
summary.simmap.Anthocyanins <- summary(simmap.Anthocyanins)

pdffn = paste0("Model.Anthocyanins2rates.ER.pdf")
pdf(file=pdffn, width=6, height=8)
plotMKmodel(pp.Anthocyanins.ER.2)
dev.off()

pdffn = paste0("Anthocyanins2rates.ER.pdf")
pdf(file=pdffn, width=6, height=60)
plotRECON(tree,pp.Anthocyanins.ER.2$states,cex=0.5, pie.cex=0.5,title="Anthocyanins 2 rates ER")
dev.off()

cols<-setNames(c("white", "black", "red", "yellow"),levels(c("(0,R1)", "(1,R1)", "(0,R2)", "(1,R2)")))
pdffn = paste0("Anthocyanins2ratesfanER.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Anthocyanins.ER.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("grey", "grey", "orange", "orange"),levels(c("(0,R1)", "(1,R1)", "(0,R2)", "(1,R2)")))
pdffn = paste0("Anthocyanins2ratesfanER.rates.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Anthocyanins.ER.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("pink", "brown", "pink", "brown"),levels(c("(0,R1)", "(1,R1)", "(0,R2)", "(1,R2)")))
pdffn = paste0("Anthocyanins2ratesfanER.color.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Anthocyanins.ER.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white", "red", "black", "yellow"),c("(0,R1)", "(0,R2)", "(1,R1)", "(1,R2)"))
pdffn = paste0("summary.simmap.Anthocyanins.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Anthocyanins, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("grey", "orange", "grey", "orange"),c("(0,R1)", "(0,R2)", "(1,R1)", "(1,R2)"))
pdffn = paste0("summary.simmap.Anthocyanins.rates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Anthocyanins, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("pink", "pink", "brown", "brown"),c("(0,R1)", "(0,R2)", "(1,R1)", "(1,R2)"))
pdffn = paste0("summary.simmap.Anthocyanins.color.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Anthocyanins, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

#Aurones
Aurones <- cbind (as.character(mydata[,12][!is.na(mydata[,8])]),mydata[,8][!is.na(mydata[,8])])
library(phytools)
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,Aurones[,1])
tree <- drop.tip(tree, tipstoremove)

pp.Aurones.ARD.2<-corHMM(tree,Aurones,rate.cat=2,node.states="marginal")
pp.Aurones.ARD.2
pp.Aurones.ARD.1<-corHMM(tree,Aurones,rate.cat=1,node.states="marginal")
pp.Aurones.ARD.1
pp.Aurones.ER.2<-corHMM(tree,Aurones,rate.cat=2, model = "ER", node.states="marginal")
pp.Aurones.ER.2
pp.Aurones.ER.1<-corHMM(tree,Aurones,rate.cat=1, model = "ER", node.states="marginal")
pp.Aurones.ER.1
pp.Aurones.ARD.3<-corHMM(tree,Aurones,rate.cat=3, node.states="marginal")
pp.Aurones.ARD.3
pp.Aurones.ER.3<-corHMM(tree,Aurones,rate.cat=3, model = "ER", node.states="marginal")
pp.Aurones.ER.3

simmap.Aurones <- makeSimmap(tree=tree, data=Aurones, model=pp.Aurones.ARD.2$solution, rate.cat=2, nSim=100, nCores=1)
summary.simmap.Aurones <- summary(simmap.Aurones)

pdffn = paste0("Model.Aurones2rates.ARD.pdf")
pdf(file=pdffn, width=6, height=8)
plotMKmodel(pp.Aurones.ARD.2)
dev.off()

pdffn = paste0("Aurones2rates.ARD.pdf")
pdf(file=pdffn, width=6, height=60)
plotRECON(tree,pp.Aurones.ARD.2$states,cex=0.5, pie.cex=0.5,title="Aurones 2 rates ARD")
dev.off()

cols<-setNames(c("white", "black", "red", "yellow"),levels(c("(0,R1)", "(1,R1)", "(0,R2)", "(1,R2)")))
pdffn = paste0("Aurones2ratesfanARD.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Aurones.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("grey", "grey", "orange", "orange"),levels(c("(0,R1)", "(1,R1)", "(0,R2)", "(1,R2)")))
pdffn = paste0("Aurones2ratesfanARD.rates.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Aurones.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("pink", "brown", "pink", "brown"),levels(c("(0,R1)", "(1,R1)", "(0,R2)", "(1,R2)")))
pdffn = paste0("Aurones2ratesfanARD.color.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Aurones.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white", "red", "black", "yellow"),levels(c("(0,R1)", "(1,R1)", "(0,R2)", "(1,R2)")))
pdffn = paste0("summary.simmap.Aurones.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Aurones, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("grey", "orange", "grey", "orange"),c("(0,R1)", "(0,R2)", "(1,R1)", "(1,R2)"))
pdffn = paste0("summary.simmap.Aurones.rates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Aurones, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("pink", "pink", "brown", "brown"),c("(0,R1)", "(0,R2)", "(1,R1)", "(1,R2)"))
pdffn = paste0("summary.simmap.Aurones.color.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Aurones, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

#Carotenoids
Carotenoids <- cbind (as.character(mydata[,12][!is.na(mydata[,9])]),mydata[,9][!is.na(mydata[,9])])
library(phytools)
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,Carotenoids[,1])
tree <- drop.tip(tree, tipstoremove)

pp.Carotenoids.ARD.2<-corHMM(tree,Carotenoids,rate.cat=2,node.states="marginal")
pp.Carotenoids.ARD.2
pp.Carotenoids.ARD.1<-corHMM(tree,Carotenoids,rate.cat=1,node.states="marginal")
pp.Carotenoids.ARD.1
pp.Carotenoids.ER.2<-corHMM(tree,Carotenoids,rate.cat=2, model = "ER", node.states="marginal")
pp.Carotenoids.ER.2
pp.Carotenoids.ER.1<-corHMM(tree,Carotenoids,rate.cat=1, model = "ER", node.states="marginal")
pp.Carotenoids.ER.1
pp.Carotenoids.ARD.3<-corHMM(tree,Carotenoids,rate.cat=3, node.states="marginal")
pp.Carotenoids.ARD.3
pp.Carotenoids.ER.3<-corHMM(tree,Carotenoids,rate.cat=3, model = "ER", node.states="marginal")
pp.Carotenoids.ER.3

simmap.Carotenoids <- makeSimmap(tree=tree, data=Carotenoids, model=pp.Carotenoids.ARD.2$solution, rate.cat=2, nSim=100, nCores=1)
summary.simmap.Carotenoids <- summary(simmap.Carotenoids)

pdffn = paste0("Model.Carotenoids2rates.ARD.pdf")
pdf(file=pdffn, width=6, height=8)
plotMKmodel(pp.Carotenoids.ARD.2)
dev.off()

pdffn = paste0("Carotenoids2rates.ARD.pdf")
pdf(file=pdffn, width=6, height=60)
plotRECON(tree,pp.Carotenoids.ARD.2$states,cex=0.5, pie.cex=0.5,title="Carotenoids 2 rates ARD")
dev.off()

cols<-setNames(c("white", "black", "red", "yellow"),levels(c("(0,R1)", "(1,R1)", "(0,R2)", "(1,R2)")))
pdffn = paste0("Carotenoids2ratesfanARD.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Carotenoids.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("grey", "grey", "orange", "orange"),levels(c("(0,R1)", "(1,R1)", "(0,R2)", "(1,R2)")))
pdffn = paste0("Carotenoids2ratesfanARD.rates.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Carotenoids.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("pink", "brown", "pink", "brown"),levels(c("(0,R1)", "(1,R1)", "(0,R2)", "(1,R2)")))
pdffn = paste0("Carotenoids2ratesfanARD.color.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Carotenoids.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white", "red", "black", "yellow"),c("(0,R1)", "(0,R2)", "(1,R1)", "(1,R2)"))
pdffn = paste0("summary.simmap.Carotenoids.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Carotenoids, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("grey", "orange", "grey", "orange"),c("(0,R1)", "(0,R2)", "(1,R1)", "(1,R2)"))
pdffn = paste0("summary.simmap.Carotenoids.rates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Carotenoids, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("pink", "pink", "brown", "brown"),c("(0,R1)", "(0,R2)", "(1,R1)", "(1,R2)"))
pdffn = paste0("summary.simmap.Carotenoids.color.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Carotenoids, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

#Chlorophylls
Chlorophylls <- cbind (as.character(mydata[,12][!is.na(mydata[,10])]),mydata[,10][!is.na(mydata[,10])])
library(phytools)
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,Chlorophylls[,1])
tree <- drop.tip(tree, tipstoremove)

pp.Chlorophylls.ARD.2<-corHMM(tree,Chlorophylls,rate.cat=2,node.states="marginal")
pp.Chlorophylls.ARD.2
pp.Chlorophylls.ARD.1<-corHMM(tree,Chlorophylls,rate.cat=1,node.states="marginal")
pp.Chlorophylls.ARD.1
pp.Chlorophylls.ER.2<-corHMM(tree,Chlorophylls,rate.cat=2, model = "ER", node.states="marginal")
pp.Chlorophylls.ER.2
pp.Chlorophylls.ER.1<-corHMM(tree,Chlorophylls,rate.cat=1, model = "ER", node.states="marginal")
pp.Chlorophylls.ER.1
pp.Chlorophylls.ARD.3<-corHMM(tree,Chlorophylls,rate.cat=3, node.states="marginal")
pp.Chlorophylls.ARD.3
pp.Chlorophylls.ER.3<-corHMM(tree,Chlorophylls,rate.cat=3, model = "ER", node.states="marginal")
pp.Chlorophylls.ER.3

simmap.Chlorophylls <- makeSimmap(tree=tree, data=Chlorophylls, model=pp.Chlorophylls.ARD.2$solution, rate.cat=2, nSim=100, nCores=1)
summary.simmap.Chlorophylls <- summary(simmap.Chlorophylls)

pdffn = paste0("Model.Chlorophylls2rates.ARD.pdf")
pdf(file=pdffn, width=6, height=8)
plotMKmodel(pp.Chlorophylls.ARD.2)
dev.off()

pdffn = paste0("Chlorophylls2rates.ARD.pdf")
pdf(file=pdffn, width=6, height=60)
plotRECON(tree,pp.Chlorophylls.ARD.2$states,cex=0.5, pie.cex=0.5,title="Chlorophylls 2 rates ARD")
dev.off()

cols<-setNames(c("white", "black", "red", "yellow"),levels(c("(0,R1)", "(1,R1)", "(0,R2)", "(1,R2)")))
pdffn = paste0("Chlorophylls2ratesfanARD.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Chlorophylls.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("grey", "grey", "orange", "orange"),levels(c("(0,R1)", "(1,R1)", "(0,R2)", "(1,R2)")))
pdffn = paste0("Chlorophylls2ratesfanARD.rates.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Chlorophylls.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("pink", "brown", "pink", "brown"),levels(c("(0,R1)", "(1,R1)", "(0,R2)", "(1,R2)")))
pdffn = paste0("Chlorophylls2ratesfanARD.color.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Chlorophylls.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white", "red", "black", "yellow"),c("(0,R1)", "(0,R2)", "(1,R1)", "(1,R2)"))
pdffn = paste0("summary.simmap.Chlorophylls.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Chlorophylls, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("grey", "orange", "grey", "orange"),c("(0,R1)", "(0,R2)", "(1,R1)", "(1,R2)"))
pdffn = paste0("summary.simmap.Chlorophylls.rates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Chlorophylls, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("pink", "pink", "brown", "brown"),c("(0,R1)", "(0,R2)", "(1,R1)", "(1,R2)"))
pdffn = paste0("summary.simmap.Chlorophylls.color.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Chlorophylls, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

#Npigments
Npigments <- cbind (as.character(mydata[,12][!is.na(mydata[,11])]),mydata[,11][!is.na(mydata[,11])])
library(phytools)
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,Npigments[,1])
tree <- drop.tip(tree, tipstoremove)

Npigments_LegendAndRate <- getStateMat4Dat(Npigments)
STEP <- dropStateMatPars(Npigments_LegendAndRate$rate.mat, c(7,10,11,2,3,6))
STEP
RateClassMat <- getRateCatMat(2)
RateClassMat
StateMats <- list(STEP, STEP)
StateMats
STEP2 <- getFullMat(StateMats, RateClassMat)

pp.Npigments.ARD.2<-corHMM(tree,Npigments,rate.cat=2,node.states="marginal")
pp.Npigments.ARD.2
pp.Npigments.ARD.1<-corHMM(tree,Npigments,rate.cat=1,node.states="marginal")
pp.Npigments.ARD.1
pp.Npigments.ER.2<-corHMM(tree,Npigments,rate.cat=2, model = "ER", node.states="marginal")
pp.Npigments.ER.2
pp.Npigments.ER.1<-corHMM(tree,Npigments,rate.cat=1, model = "ER", node.states="marginal")
pp.Npigments.ER.1
pp.Npigments.SYM.2<-corHMM(tree,Npigments,rate.cat=2, model = "SYM", node.states="marginal")
pp.Npigments.SYM.2
pp.Npigments.SYM.1<-corHMM(tree,Npigments,rate.cat=1, model = "SYM", node.states="marginal")
pp.Npigments.SYM.1
pp.Npigments.STEP.2<-corHMM(tree,Npigments,rate.cat=2, rate.mat=STEP2, node.states="marginal")
pp.Npigments.STEP.2
pp.Npigments.STEP.1<-corHMM(tree,Npigments,rate.cat=1, rate.mat=STEP, node.states="marginal")
pp.Npigments.STEP.1

#pp.Npigments.ARD.3<-corHMM(tree,Npigments,rate.cat=3, node.states="marginal")
#pp.Npigments.ARD.3
#pp.Npigments.ER.3<-corHMM(tree,Npigments,rate.cat=3, model = "ER", node.states="marginal")
#pp.Npigments.ER.3

simmap.Npigments <- makeSimmap(tree=tree, data=Npigments, model=pp.Npigments.STEP.2$solution, rate.cat=2, nSim=100, nCores=1)
summary.simmap.Npigments <- summary(simmap.Npigments)

pdffn = paste0("Model.Npigments2rates.STEP.pdf")
pdf(file=pdffn, width=6, height=8)
plotMKmodel(pp.Npigments.STEP.2)
dev.off()

pdffn = paste0("Npigments2rates.STEP.pdf")
pdf(file=pdffn, width=6, height=60)
plotRECON(tree,pp.Npigments.STEP.2$states,cex=0.5, pie.cex=0.5,title="Npigments 2 rates STEP")
dev.off()

cols<-setNames(c("white", "grey", "darkgrey", "black", "yellow", "orange", "red", "darkred"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Npigments2ratesfanSTEP.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Npigments.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("green", "green", "green", "green", "red", "red", "red", "red"),(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Npigments2ratesfanSTEP.rates.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Npigments.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("yellow", "orange", "red", "darkred", "yellow", "orange", "red", "darkred"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Npigments2ratesfanSTEP.color.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Npigments.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white", "grey", "darkgrey", "black", "yellow", "orange", "red", "darkred"),(c("(0,R1)", "(1,R1)", "(2,R1)", "(3,R1)", "(0,R2)", "(1,R2)", "(2,R2)", "(3,R2)")))
pdffn = paste0("summary.simmap.Npigments.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Npigments, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("green", "red", "green", "red", "green", "red", "green", "red"),(c("(0,R1)", "(0,R2)", "(1,R1)", "(1,R2)", "(2,R1)", "(2,R2)", "(3,R1)", "(3,R2)" 
)))
pdffn = paste0("summary.simmap.Npigments.rates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Npigments, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("yellow", "orange", "red", "darkred", "yellow", "orange", "red", "darkred"),(c("(0,R1)", "(1,R1)", "(2,R1)", "(3,R1)", "(0,R2)", "(1,R2)", "(2,R2)", "(3,R2)")))
pdffn = paste0("summary.simmap.Npigments.color.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Npigments, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

```

Independent vs. dependent evolution with corHMM

```{r}

library(corHMM)


#Anthocyanins.Aurones
Anthocyanins.Aurones <- cbind (as.character(mydata[,12][!is.na(mydata[,7]) & !is.na(mydata[,8])]),mydata[,7][!is.na(mydata[,7])& !is.na(mydata[,8])],mydata[,8][!is.na(mydata[,7])& !is.na(mydata[,8])])
library(phytools)
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,Anthocyanins.Aurones[,1])
tree <- drop.tip(tree, tipstoremove)

Anthocyanins.Aurones_LegendAndRate <- getStateMat4Dat(Anthocyanins.Aurones) 
Anthocyanins.Aurones_LegendAndRate
Anthocyanins.Aurones.ind <- Anthocyanins.Aurones_LegendAndRate$rate.mat
Anthocyanins.Aurones.ind
Anthocyanins.Aurones.ind <- equateStateMatPars(Anthocyanins.Aurones.ind, c(1,6))
Anthocyanins.Aurones.ind
Anthocyanins.Aurones.ind <- equateStateMatPars(Anthocyanins.Aurones.ind, c(1,3))
Anthocyanins.Aurones.ind
Anthocyanins.Aurones.ind <- equateStateMatPars(Anthocyanins.Aurones.ind, c(1,4))
Anthocyanins.Aurones.ind
Anthocyanins.Aurones.ind <- equateStateMatPars(Anthocyanins.Aurones.ind, c(1,2))
Anthocyanins.Aurones.ind

Anthocyanins.Aurones_LegendAndRate <- getStateMat4Dat(Anthocyanins.Aurones) 
Anthocyanins.Aurones_LegendAndRate
Anthocyanins.Aurones.x <- Anthocyanins.Aurones_LegendAndRate$rate.mat
Anthocyanins.Aurones.x
Anthocyanins.Aurones.x <- equateStateMatPars(Anthocyanins.Aurones.x, c(1,6))
Anthocyanins.Aurones.x
Anthocyanins.Aurones.x <- equateStateMatPars(Anthocyanins.Aurones.x, c(2,6))
Anthocyanins.Aurones.x

Anthocyanins.Aurones_LegendAndRate <- getStateMat4Dat(Anthocyanins.Aurones) 
Anthocyanins.Aurones_LegendAndRate
Anthocyanins.Aurones.y <- Anthocyanins.Aurones_LegendAndRate$rate.mat
Anthocyanins.Aurones.y
Anthocyanins.Aurones.y <- equateStateMatPars(Anthocyanins.Aurones.y, c(2,4))
Anthocyanins.Aurones.y
Anthocyanins.Aurones.y <- equateStateMatPars(Anthocyanins.Aurones.y, c(3,5))
Anthocyanins.Aurones.y

RateClassMat <- getRateCatMat(2)
RateClassMat
StateMats <- list(Anthocyanins.Aurones.ind, Anthocyanins.Aurones.ind)
StateMats
IND2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Anthocyanins.Aurones.x, Anthocyanins.Aurones.x)
StateMats
ARDx2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Anthocyanins.Aurones.y, Anthocyanins.Aurones.y)
StateMats
ARDy2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Anthocyanins.Aurones.x, Anthocyanins.Aurones.y)
StateMats
ARDxy2 <- getFullMat(StateMats, RateClassMat)


pp.Anthocyanins.Aurones.ARD.1<-corHMM(tree,Anthocyanins.Aurones,rate.cat=1,node.states="marginal")
pp.Anthocyanins.Aurones.ARD.1
plotMKmodel(pp.Anthocyanins.Aurones.ARD.1)
pp.Anthocyanins.Aurones.ER.1<-corHMM(tree,Anthocyanins.Aurones,rate.cat=1, model = "ER", node.states="marginal")
pp.Anthocyanins.Aurones.ER.1
plotMKmodel(pp.Anthocyanins.Aurones.ER.1)
pp.Anthocyanins.Aurones.IND.1<-corHMM(tree,Anthocyanins.Aurones,rate.cat=1,rate.mat=Anthocyanins.Aurones.ind, node.states="marginal")
pp.Anthocyanins.Aurones.IND.1
plotMKmodel(pp.Anthocyanins.Aurones.IND.1)
pp.Anthocyanins.Aurones.ARDx.1<-corHMM(tree,Anthocyanins.Aurones,rate.cat=1,rate.mat=Anthocyanins.Aurones.x, node.states="marginal")
pp.Anthocyanins.Aurones.ARDx.1
plotMKmodel(pp.Anthocyanins.Aurones.ARDx.1)
pp.Anthocyanins.Aurones.ARDy.1<-corHMM(tree,Anthocyanins.Aurones,rate.cat=1,rate.mat=Anthocyanins.Aurones.y, node.states="marginal")
pp.Anthocyanins.Aurones.ARDy.1

plotMKmodel(pp.Anthocyanins.Aurones.ARDy.1)

pp.Anthocyanins.Aurones.ARD.2<-corHMM(tree,Anthocyanins.Aurones,rate.cat=2,node.states="marginal")
pp.Anthocyanins.Aurones.ARD.2
pp.Anthocyanins.Aurones.ER.2<-corHMM(tree,Anthocyanins.Aurones,rate.cat=2, model = "ER", node.states="marginal")
pp.Anthocyanins.Aurones.ER.2

pp.Anthocyanins.Aurones.IND.2<-corHMM(tree,Anthocyanins.Aurones,rate.cat=2,rate.mat=IND2, node.states="marginal")
pp.Anthocyanins.Aurones.IND.2

pp.Anthocyanins.Aurones.ARDx.2<-corHMM(tree,Anthocyanins.Aurones,rate.cat=2,rate.mat=ARDx2, node.states="marginal")
pp.Anthocyanins.Aurones.ARDx.2

pp.Anthocyanins.Aurones.ARDy.2<-corHMM(tree,Anthocyanins.Aurones,rate.cat=2,rate.mat=ARDy2, node.states="marginal")
pp.Anthocyanins.Aurones.ARDy.2

pp.Anthocyanins.Aurones.ARDxy.2<-corHMM(tree,Anthocyanins.Aurones,rate.cat=2,rate.mat=ARDxy2, node.states="marginal")
pp.Anthocyanins.Aurones.ARDxy.2

simmap.Anthocyanins.Aurones <- makeSimmap(tree=tree, data=Anthocyanins.Aurones, model=pp.Anthocyanins.Aurones.ARDx.2$solution, rate.cat=2, nSim=100, nCores=1)
summary.simmap.Anthocyanins.Aurones <- summary(simmap.Anthocyanins.Aurones)

pdffn = paste0("Model.Anthocyanins.Aurones2rates.ARDx.pdf")
pdf(file=pdffn, width=6, height=8)
plotMKmodel(pp.Anthocyanins.Aurones.ARDx.2)
dev.off()

pdffn = paste0("Anthocyanins.Aurones2rates.ARDx.pdf")
pdf(file=pdffn, width=6, height=60)
plotRECON(tree,pp.Anthocyanins.Aurones.ARDx.2$states,cex=0.5, pie.cex=0.5,title="Anthocyanins.Aurones 2 rates ARDx")
dev.off()

cols<-setNames(c("white","lightgrey","darkgrey", "black", "red","darkorange","orange", "yellow"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Anthocyanins.Aurones2ratesfanARDx.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Anthocyanins.Aurones.ARDx.2$states,piecol=cols,cex=0.2)
dev.off()


cols<-setNames(c("white","yellow","pink", "red", "white","yellow","pink", "red"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Anthocyanins.Aurones2ratesfanARDx.color.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Anthocyanins.Aurones.ARDx.2$states,piecol=cols,cex=0.2)
dev.off()


cols<-setNames(c("white","white","white", "white", "grey","grey","grey", "grey"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Anthocyanins.Aurones2ratesfanARDx.regimes.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Anthocyanins.Aurones.ARDx.2$states,piecol=cols,cex=0.2)
dev.off()


cols<-setNames(c("white","red","lightgrey","darkorange","darkgrey", "orange","black", "yellow"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Anthocyanins.Aurones.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Anthocyanins.Aurones, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()


cols<-setNames(c("white","grey","white","grey","white","grey","white","grey"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Anthocyanins.Aurones.rates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Anthocyanins.Aurones, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("white","white","yellow","yellow","pink","pink", "red","red"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Anthocyanins.Aurones.color.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Anthocyanins.Aurones, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()


#Anthocyanins.Carotenoids
Anthocyanins.Carotenoids <- cbind (as.character(mydata[,12][!is.na(mydata[,7]) & !is.na(mydata[,9])]),mydata[,7][!is.na(mydata[,7])& !is.na(mydata[,9])],mydata[,9][!is.na(mydata[,7])& !is.na(mydata[,9])])
library(phytools)
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,Anthocyanins.Carotenoids[,1])
tree <- drop.tip(tree, tipstoremove)

Anthocyanins.Carotenoids_LegendAndRate <- getStateMat4Dat(Anthocyanins.Carotenoids) 
Anthocyanins.Carotenoids_LegendAndRate
Anthocyanins.Carotenoids.ind <- Anthocyanins.Carotenoids_LegendAndRate$rate.mat
Anthocyanins.Carotenoids.ind
Anthocyanins.Carotenoids.ind <- equateStateMatPars(Anthocyanins.Carotenoids.ind, c(1,6))
Anthocyanins.Carotenoids.ind
Anthocyanins.Carotenoids.ind <- equateStateMatPars(Anthocyanins.Carotenoids.ind, c(1,3))
Anthocyanins.Carotenoids.ind
Anthocyanins.Carotenoids.ind <- equateStateMatPars(Anthocyanins.Carotenoids.ind, c(1,4))
Anthocyanins.Carotenoids.ind
Anthocyanins.Carotenoids.ind <- equateStateMatPars(Anthocyanins.Carotenoids.ind, c(1,2))
Anthocyanins.Carotenoids.ind

Anthocyanins.Carotenoids_LegendAndRate <- getStateMat4Dat(Anthocyanins.Carotenoids) 
Anthocyanins.Carotenoids_LegendAndRate
Anthocyanins.Carotenoids.x <- Anthocyanins.Carotenoids_LegendAndRate$rate.mat
Anthocyanins.Carotenoids.x
Anthocyanins.Carotenoids.x <- equateStateMatPars(Anthocyanins.Carotenoids.x, c(1,6))
Anthocyanins.Carotenoids.x
Anthocyanins.Carotenoids.x <- equateStateMatPars(Anthocyanins.Carotenoids.x, c(2,6))
Anthocyanins.Carotenoids.x

Anthocyanins.Carotenoids_LegendAndRate <- getStateMat4Dat(Anthocyanins.Carotenoids) 
Anthocyanins.Carotenoids_LegendAndRate
Anthocyanins.Carotenoids.y <- Anthocyanins.Carotenoids_LegendAndRate$rate.mat
Anthocyanins.Carotenoids.y
Anthocyanins.Carotenoids.y <- equateStateMatPars(Anthocyanins.Carotenoids.y, c(2,4))
Anthocyanins.Carotenoids.y
Anthocyanins.Carotenoids.y <- equateStateMatPars(Anthocyanins.Carotenoids.y, c(3,5))
Anthocyanins.Carotenoids.y

RateClassMat <- getRateCatMat(2)
RateClassMat
StateMats <- list(Anthocyanins.Carotenoids.ind, Anthocyanins.Carotenoids.ind)
StateMats
IND2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Anthocyanins.Carotenoids.x, Anthocyanins.Carotenoids.x)
StateMats
ARDx2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Anthocyanins.Carotenoids.y, Anthocyanins.Carotenoids.y)
StateMats
ARDy2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Anthocyanins.Carotenoids.x, Anthocyanins.Carotenoids.y)
StateMats
ARDxy2 <- getFullMat(StateMats, RateClassMat)

pp.Anthocyanins.Carotenoids.ARD.1<-corHMM(tree,Anthocyanins.Carotenoids,rate.cat=1,node.states="marginal")
pp.Anthocyanins.Carotenoids.ARD.1
plotMKmodel(pp.Anthocyanins.Carotenoids.ARD.1)
pp.Anthocyanins.Carotenoids.ER.1<-corHMM(tree,Anthocyanins.Carotenoids,rate.cat=1, model = "ER", node.states="marginal")
pp.Anthocyanins.Carotenoids.ER.1
plotMKmodel(pp.Anthocyanins.Carotenoids.ER.1)
pp.Anthocyanins.Carotenoids.IND.1<-corHMM(tree,Anthocyanins.Carotenoids,rate.cat=1,rate.mat=Anthocyanins.Carotenoids.ind, node.states="marginal")
pp.Anthocyanins.Carotenoids.IND.1
plotMKmodel(pp.Anthocyanins.Carotenoids.IND.1)
pp.Anthocyanins.Carotenoids.ARDx.1<-corHMM(tree,Anthocyanins.Carotenoids,rate.cat=1,rate.mat=Anthocyanins.Carotenoids.x, node.states="marginal")
pp.Anthocyanins.Carotenoids.ARDx.1
plotMKmodel(pp.Anthocyanins.Carotenoids.ARDx.1)
pp.Anthocyanins.Carotenoids.ARDy.1<-corHMM(tree,Anthocyanins.Carotenoids,rate.cat=1,rate.mat=Anthocyanins.Carotenoids.y, node.states="marginal")
pp.Anthocyanins.Carotenoids.ARDy.1
plotMKmodel(pp.Anthocyanins.Carotenoids.ARDy.1)

pp.Anthocyanins.Carotenoids.ARD.2<-corHMM(tree,Anthocyanins.Carotenoids,rate.cat=2,node.states="marginal")
pp.Anthocyanins.Carotenoids.ARD.2
pp.Anthocyanins.Carotenoids.ER.2<-corHMM(tree,Anthocyanins.Carotenoids,rate.cat=2, model = "ER", node.states="marginal")
pp.Anthocyanins.Carotenoids.ER.2

pp.Anthocyanins.Carotenoids.IND.2<-corHMM(tree,Anthocyanins.Carotenoids,rate.cat=2,rate.mat=IND2, node.states="marginal")
pp.Anthocyanins.Carotenoids.IND.2

pp.Anthocyanins.Carotenoids.ARDx.2<-corHMM(tree,Anthocyanins.Carotenoids,rate.cat=2,rate.mat=ARDx2, node.states="marginal")
pp.Anthocyanins.Carotenoids.ARDx.2

pp.Anthocyanins.Carotenoids.ARDy.2<-corHMM(tree,Anthocyanins.Carotenoids,rate.cat=2,rate.mat=ARDy2, node.states="marginal")
pp.Anthocyanins.Carotenoids.ARDy.2

pp.Anthocyanins.Carotenoids.ARDxy.2<-corHMM(tree,Anthocyanins.Carotenoids,rate.cat=2,rate.mat=ARDxy2, node.states="marginal")
pp.Anthocyanins.Carotenoids.ARDxy.2

simmap.Anthocyanins.Carotenoids <- makeSimmap(tree=tree, data=Anthocyanins.Carotenoids, model=pp.Anthocyanins.Carotenoids.ARDx.2$solution, rate.cat=2, nSim=100, nCores=1)
summary.simmap.Anthocyanins.Carotenoids <- summary(simmap.Anthocyanins.Carotenoids)

pdffn = paste0("Model.Anthocyanins.Carotenoids2rates.ARDx.pdf")
pdf(file=pdffn, width=6, height=8)
plotMKmodel(pp.Anthocyanins.Carotenoids.ARDx.2)
dev.off()

pdffn = paste0("Anthocyanins.Carotenoids2rates.ARDx.pdf")
pdf(file=pdffn, width=6, height=60)
plotRECON(tree,pp.Anthocyanins.Carotenoids.ARDx.2$states,cex=0.5, pie.cex=0.5,title="Anthocyanins.Carotenoids 2 rates ARDx")
dev.off()


cols<-setNames(c("white","lightgrey","darkgrey", "black", "red","darkorange","orange", "yellow"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Anthocyanins.Carotenoids2ratesfanARDx.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Anthocyanins.Carotenoids.ARDx.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","yellow","pink", "red", "white","yellow","pink", "red"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Anthocyanins.Carotenoids2ratesfanARDx.color.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Anthocyanins.Carotenoids.ARDx.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","white","white", "white", "grey","grey","grey", "grey"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Anthocyanins.Carotenoids2ratesfanARDx.rates.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Anthocyanins.Carotenoids.ARDx.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","red","lightgrey","darkorange","darkgrey", "orange","black", "yellow"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Anthocyanins.Carotenoids.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Anthocyanins.Carotenoids, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()


cols<-setNames(c("white","grey","white","grey","white","grey","white","grey"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Anthocyanins.Carotenoids.rates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Anthocyanins.Carotenoids, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("white","white","yellow","yellow","pink","pink", "red","red"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Anthocyanins.Carotenoids.color.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Anthocyanins.Carotenoids, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()


#Anthocyanins.Chlorophylls
Anthocyanins.Chlorophylls <- cbind (as.character(mydata[,12][!is.na(mydata[,7]) & !is.na(mydata[,10])]),mydata[,7][!is.na(mydata[,7])& !is.na(mydata[,10])],mydata[,10][!is.na(mydata[,7])& !is.na(mydata[,10])])
library(phytools)
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,Anthocyanins.Chlorophylls[,1])
tree <- drop.tip(tree, tipstoremove)

Anthocyanins.Chlorophylls_LegendAndRate <- getStateMat4Dat(Anthocyanins.Chlorophylls) 
Anthocyanins.Chlorophylls_LegendAndRate
Anthocyanins.Chlorophylls.ind <- Anthocyanins.Chlorophylls_LegendAndRate$rate.mat
Anthocyanins.Chlorophylls.ind
Anthocyanins.Chlorophylls.ind <- equateStateMatPars(Anthocyanins.Chlorophylls.ind, c(1,6))
Anthocyanins.Chlorophylls.ind
Anthocyanins.Chlorophylls.ind <- equateStateMatPars(Anthocyanins.Chlorophylls.ind, c(1,3))
Anthocyanins.Chlorophylls.ind
Anthocyanins.Chlorophylls.ind <- equateStateMatPars(Anthocyanins.Chlorophylls.ind, c(1,4))
Anthocyanins.Chlorophylls.ind
Anthocyanins.Chlorophylls.ind <- equateStateMatPars(Anthocyanins.Chlorophylls.ind, c(1,2))
Anthocyanins.Chlorophylls.ind

Anthocyanins.Chlorophylls_LegendAndRate <- getStateMat4Dat(Anthocyanins.Chlorophylls) 
Anthocyanins.Chlorophylls_LegendAndRate
Anthocyanins.Chlorophylls.x <- Anthocyanins.Chlorophylls_LegendAndRate$rate.mat
Anthocyanins.Chlorophylls.x
Anthocyanins.Chlorophylls.x <- equateStateMatPars(Anthocyanins.Chlorophylls.x, c(1,6))
Anthocyanins.Chlorophylls.x
Anthocyanins.Chlorophylls.x <- equateStateMatPars(Anthocyanins.Chlorophylls.x, c(2,6))
Anthocyanins.Chlorophylls.x

Anthocyanins.Chlorophylls_LegendAndRate <- getStateMat4Dat(Anthocyanins.Chlorophylls) 
Anthocyanins.Chlorophylls_LegendAndRate
Anthocyanins.Chlorophylls.y <- Anthocyanins.Chlorophylls_LegendAndRate$rate.mat
Anthocyanins.Chlorophylls.y
Anthocyanins.Chlorophylls.y <- equateStateMatPars(Anthocyanins.Chlorophylls.y, c(2,4))
Anthocyanins.Chlorophylls.y
Anthocyanins.Chlorophylls.y <- equateStateMatPars(Anthocyanins.Chlorophylls.y, c(3,5))
Anthocyanins.Chlorophylls.y

RateClassMat <- getRateCatMat(2)
RateClassMat
StateMats <- list(Anthocyanins.Chlorophylls.ind, Anthocyanins.Chlorophylls.ind)
StateMats
IND2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Anthocyanins.Chlorophylls.x, Anthocyanins.Chlorophylls.x)
StateMats
ARDx2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Anthocyanins.Chlorophylls.y, Anthocyanins.Chlorophylls.y)
StateMats
ARDy2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Anthocyanins.Chlorophylls.x, Anthocyanins.Chlorophylls.y)
StateMats
ARDxy2 <- getFullMat(StateMats, RateClassMat)

pp.Anthocyanins.Chlorophylls.ARD.1<-corHMM(tree,Anthocyanins.Chlorophylls,rate.cat=1,node.states="marginal")
pp.Anthocyanins.Chlorophylls.ARD.1
plotMKmodel(pp.Anthocyanins.Chlorophylls.ARD.1)
pp.Anthocyanins.Chlorophylls.ER.1<-corHMM(tree,Anthocyanins.Chlorophylls,rate.cat=1, model = "ER", node.states="marginal")
pp.Anthocyanins.Chlorophylls.ER.1
plotMKmodel(pp.Anthocyanins.Chlorophylls.ER.1)
pp.Anthocyanins.Chlorophylls.IND.1<-corHMM(tree,Anthocyanins.Chlorophylls,rate.cat=1,rate.mat=Anthocyanins.Chlorophylls.ind, node.states="marginal")
pp.Anthocyanins.Chlorophylls.IND.1
plotMKmodel(pp.Anthocyanins.Chlorophylls.IND.1)
pp.Anthocyanins.Chlorophylls.ARDx.1<-corHMM(tree,Anthocyanins.Chlorophylls,rate.cat=1,rate.mat=Anthocyanins.Chlorophylls.x, node.states="marginal")
pp.Anthocyanins.Chlorophylls.ARDx.1
plotMKmodel(pp.Anthocyanins.Chlorophylls.ARDx.1)
pp.Anthocyanins.Chlorophylls.ARDy.1<-corHMM(tree,Anthocyanins.Chlorophylls,rate.cat=1,rate.mat=Anthocyanins.Chlorophylls.y, node.states="marginal")
pp.Anthocyanins.Chlorophylls.ARDy.1
plotMKmodel(pp.Anthocyanins.Chlorophylls.ARDy.1)

pp.Anthocyanins.Chlorophylls.ARD.2<-corHMM(tree,Anthocyanins.Chlorophylls,rate.cat=2,node.states="marginal")
pp.Anthocyanins.Chlorophylls.ARD.2
pp.Anthocyanins.Chlorophylls.ER.2<-corHMM(tree,Anthocyanins.Chlorophylls,rate.cat=2, model = "ER", node.states="marginal")
pp.Anthocyanins.Chlorophylls.ER.2

pp.Anthocyanins.Chlorophylls.IND.2<-corHMM(tree,Anthocyanins.Chlorophylls,rate.cat=2,rate.mat=IND2, node.states="marginal")
pp.Anthocyanins.Chlorophylls.IND.2

pp.Anthocyanins.Chlorophylls.ARDx.2<-corHMM(tree,Anthocyanins.Chlorophylls,rate.cat=2,rate.mat=ARDx2, node.states="marginal")
pp.Anthocyanins.Chlorophylls.ARDx.2

pp.Anthocyanins.Chlorophylls.ARDy.2<-corHMM(tree,Anthocyanins.Chlorophylls,rate.cat=2,rate.mat=ARDy2, node.states="marginal")
pp.Anthocyanins.Chlorophylls.ARDy.2

pp.Anthocyanins.Chlorophylls.ARDxy.2<-corHMM(tree,Anthocyanins.Chlorophylls,rate.cat=2,rate.mat=ARDxy2, node.states="marginal")
pp.Anthocyanins.Chlorophylls.ARDxy.2

simmap.Anthocyanins.Chlorophylls <- makeSimmap(tree=tree, data=Anthocyanins.Chlorophylls, model=pp.Anthocyanins.Chlorophylls.ARDxy.2$solution, rate.cat=2, nSim=100, nCores=1)
summary.simmap.Anthocyanins.Chlorophylls <-summary(simmap.Anthocyanins.Chlorophylls)

pdffn = paste0("Model.Anthocyanins.Chlorophylls2rates.ARDxy.pdf")
pdf(file=pdffn, width=6, height=8)
plotMKmodel(pp.Anthocyanins.Chlorophylls.ARDxy.2)
dev.off()

pdffn = paste0("Anthocyanins.Chlorophylls2rates.ARDxy.pdf")
pdf(file=pdffn, width=6, height=60)
plotRECON(tree,pp.Anthocyanins.Chlorophylls.ARDxy.2$states,cex=0.5, pie.cex=0.5,title="Anthocyanins.Chlorophylls 2 rates ARDxy")
dev.off()


cols<-setNames(c("white","lightgrey","darkgrey", "black", "red","darkorange","orange", "yellow"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Anthocyanins.Chlorophylls2ratesfanARDxy.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Anthocyanins.Chlorophylls.ARDxy.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","yellow","pink", "red", "white","yellow","pink", "red"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Anthocyanins.Chlorophylls2ratesfanARDxy.color.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Anthocyanins.Chlorophylls.ARDxy.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","white","white", "white", "grey","grey","grey", "grey"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Anthocyanins.Chlorophylls2ratesfanARDxy.rates.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Anthocyanins.Chlorophylls.ARDxy.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","red","lightgrey","darkorange","darkgrey", "orange","black", "yellow"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Anthocyanins.Chlorophylls.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Anthocyanins.Chlorophylls, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()


cols<-setNames(c("white","grey","white","grey","white","grey","white","grey"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Anthocyanins.Chlorophylls.rates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Anthocyanins.Chlorophylls, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("white","white","yellow","yellow","pink","pink", "red","red"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Anthocyanins.Chlorophylls.color.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Anthocyanins.Chlorophylls, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

#Carotenoids.Aurones
Carotenoids.Aurones <- cbind (as.character(mydata[,12][!is.na(mydata[,9]) & !is.na(mydata[,8])]),mydata[,9][!is.na(mydata[,9])& !is.na(mydata[,8])],mydata[,8][!is.na(mydata[,9])& !is.na(mydata[,8])])
library(phytools)
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,Carotenoids.Aurones[,1])
tree <- drop.tip(tree, tipstoremove)

Carotenoids.Aurones_LegendAndRate <- getStateMat4Dat(Carotenoids.Aurones) 
Carotenoids.Aurones_LegendAndRate
Carotenoids.Aurones.ind <- Carotenoids.Aurones_LegendAndRate$rate.mat
Carotenoids.Aurones.ind
Carotenoids.Aurones.ind <- equateStateMatPars(Carotenoids.Aurones.ind, c(1,6))
Carotenoids.Aurones.ind
Carotenoids.Aurones.ind <- equateStateMatPars(Carotenoids.Aurones.ind, c(1,3))
Carotenoids.Aurones.ind
Carotenoids.Aurones.ind <- equateStateMatPars(Carotenoids.Aurones.ind, c(1,4))
Carotenoids.Aurones.ind
Carotenoids.Aurones.ind <- equateStateMatPars(Carotenoids.Aurones.ind, c(1,2))
Carotenoids.Aurones.ind

Carotenoids.Aurones_LegendAndRate <- getStateMat4Dat(Carotenoids.Aurones) 
Carotenoids.Aurones_LegendAndRate
Carotenoids.Aurones.x <- Carotenoids.Aurones_LegendAndRate$rate.mat
Carotenoids.Aurones.x
Carotenoids.Aurones.x <- equateStateMatPars(Carotenoids.Aurones.x, c(1,6))
Carotenoids.Aurones.x
Carotenoids.Aurones.x <- equateStateMatPars(Carotenoids.Aurones.x, c(2,6))
Carotenoids.Aurones.x

Carotenoids.Aurones_LegendAndRate <- getStateMat4Dat(Carotenoids.Aurones) 
Carotenoids.Aurones_LegendAndRate
Carotenoids.Aurones.y <- Carotenoids.Aurones_LegendAndRate$rate.mat
Carotenoids.Aurones.y
Carotenoids.Aurones.y <- equateStateMatPars(Carotenoids.Aurones.y, c(2,4))
Carotenoids.Aurones.y
Carotenoids.Aurones.y <- equateStateMatPars(Carotenoids.Aurones.y, c(3,5))
Carotenoids.Aurones.y

RateClassMat <- getRateCatMat(2)
RateClassMat
StateMats <- list(Carotenoids.Aurones.ind, Carotenoids.Aurones.ind)
StateMats
IND2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Carotenoids.Aurones.x, Carotenoids.Aurones.x)
StateMats
ARDx2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Carotenoids.Aurones.y, Carotenoids.Aurones.y)
StateMats
ARDy2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Carotenoids.Aurones.x, Carotenoids.Aurones.y)
StateMats
ARDxy2 <- getFullMat(StateMats, RateClassMat)

pp.Carotenoids.Aurones.ARD.1<-corHMM(tree,Carotenoids.Aurones,rate.cat=1,node.states="marginal")
pp.Carotenoids.Aurones.ARD.1
plotMKmodel(pp.Carotenoids.Aurones.ARD.1)
pp.Carotenoids.Aurones.ER.1<-corHMM(tree,Carotenoids.Aurones,rate.cat=1, model = "ER", node.states="marginal")
pp.Carotenoids.Aurones.ER.1
plotMKmodel(pp.Carotenoids.Aurones.ER.1)
pp.Carotenoids.Aurones.IND.1<-corHMM(tree,Carotenoids.Aurones,rate.cat=1,rate.mat=Carotenoids.Aurones.ind, node.states="marginal")
pp.Carotenoids.Aurones.IND.1
plotMKmodel(pp.Carotenoids.Aurones.IND.1)
pp.Carotenoids.Aurones.ARDx.1<-corHMM(tree,Carotenoids.Aurones,rate.cat=1,rate.mat=Carotenoids.Aurones.x, node.states="marginal")
pp.Carotenoids.Aurones.ARDx.1
plotMKmodel(pp.Carotenoids.Aurones.ARDx.1)
pp.Carotenoids.Aurones.ARDy.1<-corHMM(tree,Carotenoids.Aurones,rate.cat=1,rate.mat=Carotenoids.Aurones.y, node.states="marginal")
pp.Carotenoids.Aurones.ARDy.1
plotMKmodel(pp.Carotenoids.Aurones.ARDy.1)

pp.Carotenoids.Aurones.ARD.2<-corHMM(tree,Carotenoids.Aurones,rate.cat=2,node.states="marginal")
pp.Carotenoids.Aurones.ARD.2
pp.Carotenoids.Aurones.ER.2<-corHMM(tree,Carotenoids.Aurones,rate.cat=2, model = "ER", node.states="marginal")
pp.Carotenoids.Aurones.ER.2

pp.Carotenoids.Aurones.IND.2<-corHMM(tree,Carotenoids.Aurones,rate.cat=2,rate.mat=IND2, node.states="marginal")
pp.Carotenoids.Aurones.IND.2

pp.Carotenoids.Aurones.ARDx.2<-corHMM(tree,Carotenoids.Aurones,rate.cat=2,rate.mat=ARDx2, node.states="marginal")
pp.Carotenoids.Aurones.ARDx.2

pp.Carotenoids.Aurones.ARDy.2<-corHMM(tree,Carotenoids.Aurones,rate.cat=2,rate.mat=ARDy2, node.states="marginal")
pp.Carotenoids.Aurones.ARDy.2

pp.Carotenoids.Aurones.ARDxy.2<-corHMM(tree,Carotenoids.Aurones,rate.cat=2,rate.mat=ARDxy2, node.states="marginal")
pp.Carotenoids.Aurones.ARDxy.2

simmap.Carotenoids.Aurones <- makeSimmap(tree=tree, data=Carotenoids.Aurones, model=pp.Carotenoids.Aurones.ARD.2$solution, rate.cat=2, nSim=100, nCores=1)
summary.simmap.Carotenoids.Aurones <- summary(simmap.Carotenoids.Aurones)

pdffn = paste0("Model.Carotenoids.Aurones2rates.ARD.pdf")
pdf(file=pdffn, width=6, height=8)
plotMKmodel(pp.Carotenoids.Aurones.ARD.2)
dev.off()

pdffn = paste0("Carotenoids.Aurones2rates.ARD.pdf")
pdf(file=pdffn, width=6, height=60)
plotRECON(tree,pp.Carotenoids.Aurones.ARD.2$states,cex=0.5, pie.cex=0.5,title="Carotenoids.Aurones 2 rates ARD")
dev.off()


cols<-setNames(c("white","lightgrey","darkgrey", "black", "red","darkorange","orange", "yellow"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Carotenoids.Aurones2ratesfanARD.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Carotenoids.Aurones.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","yellow","pink", "red", "white","yellow","pink", "red"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Carotenoids.Aurones2ratesfanARD.color.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Carotenoids.Aurones.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","white","white", "white", "grey","grey","grey", "grey"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Carotenoids.Aurones2ratesfanARD.rates.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Carotenoids.Aurones.ARD.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","red","lightgrey","darkorange","darkgrey", "orange","black", "yellow"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Carotenoids.Aurones.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Carotenoids.Aurones, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()


cols<-setNames(c("white","grey","white","grey","white","grey","white","grey"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Carotenoids.Aurones.rates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Carotenoids.Aurones, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("white","white","yellow","yellow","pink","pink", "red","red"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Carotenoids.Aurones.color.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Carotenoids.Aurones, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

#Carotenoids.Chlorophylls
Carotenoids.Chlorophylls <- cbind (as.character(mydata[,12][!is.na(mydata[,9]) & !is.na(mydata[,10])]),mydata[,9][!is.na(mydata[,9])& !is.na(mydata[,10])],mydata[,10][!is.na(mydata[,9])& !is.na(mydata[,10])])
library(phytools)
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,Carotenoids.Chlorophylls[,1])
tree <- drop.tip(tree, tipstoremove)

Carotenoids.Chlorophylls_LegendAndRate <- getStateMat4Dat(Carotenoids.Chlorophylls) 
Carotenoids.Chlorophylls_LegendAndRate
Carotenoids.Chlorophylls.ind <- Carotenoids.Chlorophylls_LegendAndRate$rate.mat
Carotenoids.Chlorophylls.ind
Carotenoids.Chlorophylls.ind <- equateStateMatPars(Carotenoids.Chlorophylls.ind, c(1,6))
Carotenoids.Chlorophylls.ind
Carotenoids.Chlorophylls.ind <- equateStateMatPars(Carotenoids.Chlorophylls.ind, c(1,3))
Carotenoids.Chlorophylls.ind
Carotenoids.Chlorophylls.ind <- equateStateMatPars(Carotenoids.Chlorophylls.ind, c(1,4))
Carotenoids.Chlorophylls.ind
Carotenoids.Chlorophylls.ind <- equateStateMatPars(Carotenoids.Chlorophylls.ind, c(1,2))
Carotenoids.Chlorophylls.ind

Carotenoids.Chlorophylls_LegendAndRate <- getStateMat4Dat(Carotenoids.Chlorophylls) 
Carotenoids.Chlorophylls_LegendAndRate
Carotenoids.Chlorophylls.x <- Carotenoids.Chlorophylls_LegendAndRate$rate.mat
Carotenoids.Chlorophylls.x
Carotenoids.Chlorophylls.x <- equateStateMatPars(Carotenoids.Chlorophylls.x, c(1,6))
Carotenoids.Chlorophylls.x
Carotenoids.Chlorophylls.x <- equateStateMatPars(Carotenoids.Chlorophylls.x, c(2,6))
Carotenoids.Chlorophylls.x

Carotenoids.Chlorophylls_LegendAndRate <- getStateMat4Dat(Carotenoids.Chlorophylls) 
Carotenoids.Chlorophylls_LegendAndRate
Carotenoids.Chlorophylls.y <- Carotenoids.Chlorophylls_LegendAndRate$rate.mat
Carotenoids.Chlorophylls.y
Carotenoids.Chlorophylls.y <- equateStateMatPars(Carotenoids.Chlorophylls.y, c(2,4))
Carotenoids.Chlorophylls.y
Carotenoids.Chlorophylls.y <- equateStateMatPars(Carotenoids.Chlorophylls.y, c(3,5))
Carotenoids.Chlorophylls.y

RateClassMat <- getRateCatMat(2)
RateClassMat
StateMats <- list(Carotenoids.Chlorophylls.ind, Carotenoids.Chlorophylls.ind)
StateMats
IND2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Carotenoids.Chlorophylls.x, Carotenoids.Chlorophylls.x)
StateMats
ARDx2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Carotenoids.Chlorophylls.y, Carotenoids.Chlorophylls.y)
StateMats
ARDy2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Carotenoids.Chlorophylls.x, Carotenoids.Chlorophylls.y)
StateMats
ARDxy2 <- getFullMat(StateMats, RateClassMat)

pp.Carotenoids.Chlorophylls.ARD.1<-corHMM(tree,Carotenoids.Chlorophylls,rate.cat=1,node.states="marginal")
pp.Carotenoids.Chlorophylls.ARD.1
plotMKmodel(pp.Carotenoids.Chlorophylls.ARD.1)
pp.Carotenoids.Chlorophylls.ER.1<-corHMM(tree,Carotenoids.Chlorophylls,rate.cat=1, model = "ER", node.states="marginal")
pp.Carotenoids.Chlorophylls.ER.1
plotMKmodel(pp.Carotenoids.Chlorophylls.ER.1)
pp.Carotenoids.Chlorophylls.IND.1<-corHMM(tree,Carotenoids.Chlorophylls,rate.cat=1,rate.mat=Carotenoids.Chlorophylls.ind, node.states="marginal")
pp.Carotenoids.Chlorophylls.IND.1
plotMKmodel(pp.Carotenoids.Chlorophylls.IND.1)
pp.Carotenoids.Chlorophylls.ARDx.1<-corHMM(tree,Carotenoids.Chlorophylls,rate.cat=1,rate.mat=Carotenoids.Chlorophylls.x, node.states="marginal")
pp.Carotenoids.Chlorophylls.ARDx.1
plotMKmodel(pp.Carotenoids.Chlorophylls.ARDx.1)
pp.Carotenoids.Chlorophylls.ARDy.1<-corHMM(tree,Carotenoids.Chlorophylls,rate.cat=1,rate.mat=Carotenoids.Chlorophylls.y, node.states="marginal")
pp.Carotenoids.Chlorophylls.ARDy.1
plotMKmodel(pp.Carotenoids.Chlorophylls.ARDy.1)

pp.Carotenoids.Chlorophylls.ARD.2<-corHMM(tree,Carotenoids.Chlorophylls,rate.cat=2,node.states="marginal")
pp.Carotenoids.Chlorophylls.ARD.2
pp.Carotenoids.Chlorophylls.ER.2<-corHMM(tree,Carotenoids.Chlorophylls,rate.cat=2, model = "ER", node.states="marginal")
pp.Carotenoids.Chlorophylls.ER.2

pp.Carotenoids.Chlorophylls.IND.2<-corHMM(tree,Carotenoids.Chlorophylls,rate.cat=2,rate.mat=IND2, node.states="marginal")
pp.Carotenoids.Chlorophylls.IND.2

pp.Carotenoids.Chlorophylls.ARDx.2<-corHMM(tree,Carotenoids.Chlorophylls,rate.cat=2,rate.mat=ARDx2, node.states="marginal")
pp.Carotenoids.Chlorophylls.ARDx.2

pp.Carotenoids.Chlorophylls.ARDy.2<-corHMM(tree,Carotenoids.Chlorophylls,rate.cat=2,rate.mat=ARDy2, node.states="marginal")
pp.Carotenoids.Chlorophylls.ARDy.2

pp.Carotenoids.Chlorophylls.ARDxy.2<-corHMM(tree,Carotenoids.Chlorophylls,rate.cat=2,rate.mat=ARDxy2, node.states="marginal")
pp.Carotenoids.Chlorophylls.ARDxy.2

simmap.Carotenoids.Chlorophylls <- makeSimmap(tree=tree, data=Carotenoids.Chlorophylls, model=pp.Carotenoids.Chlorophylls.ARDy.2$solution, rate.cat=2, nSim=100, nCores=1)
summary.simmap.Carotenoids.Chlorophylls <- summary(simmap.Carotenoids.Chlorophylls)

pdffn = paste0("Model.Carotenoids.Chlorophylls2rates.ARDy.pdf")
pdf(file=pdffn, width=6, height=8)
plotMKmodel(pp.Carotenoids.Chlorophylls.ARDy.2)
dev.off()

pdffn = paste0("Carotenoids.Chlorophylls2rates.ARDy.pdf")
pdf(file=pdffn, width=6, height=60)
plotRECON(tree,pp.Carotenoids.Chlorophylls.ARDy.2$states,cex=0.5, pie.cex=0.5,title="Carotenoids.Chlorophylls 2 rates ARDy")
dev.off()


cols<-setNames(c("white","lightgrey","darkgrey", "black", "red","darkorange","orange", "yellow"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Carotenoids.Chlorophylls2ratesfanARDy.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Carotenoids.Chlorophylls.ARDy.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","yellow","pink", "red", "white","yellow","pink", "red"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Carotenoids.Chlorophylls2ratesfanARDy.color.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Carotenoids.Chlorophylls.ARDy.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","white","white", "white", "grey","grey","grey", "grey"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Carotenoids.Chlorophylls2ratesfanARDy.rates.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Carotenoids.Chlorophylls.ARDy.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","red","lightgrey","darkorange","darkgrey", "orange","black", "yellow"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Carotenoids.Chlorophylls.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Carotenoids.Chlorophylls, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()


cols<-setNames(c("white","grey","white","grey","white","grey","white","grey"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Carotenoids.Chlorophylls.rates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Carotenoids.Chlorophylls, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("white","white","yellow","yellow","pink","pink", "red","red"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Carotenoids.Chlorophylls.color.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Carotenoids.Chlorophylls, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

#Aurones.Chlorophylls
Aurones.Chlorophylls <- cbind (as.character(mydata[,12][!is.na(mydata[,8]) & !is.na(mydata[,10])]),mydata[,8][!is.na(mydata[,8])& !is.na(mydata[,10])],mydata[,10][!is.na(mydata[,8])& !is.na(mydata[,10])])
library(phytools)
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,Aurones.Chlorophylls[,1])
tree <- drop.tip(tree, tipstoremove)

Aurones.Chlorophylls_LegendAndRate <- getStateMat4Dat(Aurones.Chlorophylls) 
Aurones.Chlorophylls_LegendAndRate
Aurones.Chlorophylls.ind <- Aurones.Chlorophylls_LegendAndRate$rate.mat
Aurones.Chlorophylls.ind
Aurones.Chlorophylls.ind <- equateStateMatPars(Aurones.Chlorophylls.ind, c(1,6))
Aurones.Chlorophylls.ind
Aurones.Chlorophylls.ind <- equateStateMatPars(Aurones.Chlorophylls.ind, c(1,3))
Aurones.Chlorophylls.ind
Aurones.Chlorophylls.ind <- equateStateMatPars(Aurones.Chlorophylls.ind, c(1,4))
Aurones.Chlorophylls.ind
Aurones.Chlorophylls.ind <- equateStateMatPars(Aurones.Chlorophylls.ind, c(1,2))
Aurones.Chlorophylls.ind

Aurones.Chlorophylls_LegendAndRate <- getStateMat4Dat(Aurones.Chlorophylls) 
Aurones.Chlorophylls_LegendAndRate
Aurones.Chlorophylls.x <- Aurones.Chlorophylls_LegendAndRate$rate.mat
Aurones.Chlorophylls.x
Aurones.Chlorophylls.x <- equateStateMatPars(Aurones.Chlorophylls.x, c(1,6))
Aurones.Chlorophylls.x
Aurones.Chlorophylls.x <- equateStateMatPars(Aurones.Chlorophylls.x, c(2,6))
Aurones.Chlorophylls.x

Aurones.Chlorophylls_LegendAndRate <- getStateMat4Dat(Aurones.Chlorophylls) 
Aurones.Chlorophylls_LegendAndRate
Aurones.Chlorophylls.y <- Aurones.Chlorophylls_LegendAndRate$rate.mat
Aurones.Chlorophylls.y
Aurones.Chlorophylls.y <- equateStateMatPars(Aurones.Chlorophylls.y, c(2,4))
Aurones.Chlorophylls.y
Aurones.Chlorophylls.y <- equateStateMatPars(Aurones.Chlorophylls.y, c(3,5))
Aurones.Chlorophylls.y

RateClassMat <- getRateCatMat(2)
RateClassMat
StateMats <- list(Aurones.Chlorophylls.ind, Aurones.Chlorophylls.ind)
StateMats
IND2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Aurones.Chlorophylls.x, Aurones.Chlorophylls.x)
StateMats
ARDx2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Aurones.Chlorophylls.y, Aurones.Chlorophylls.y)
StateMats
ARDy2 <- getFullMat(StateMats, RateClassMat)
StateMats <- list(Aurones.Chlorophylls.x, Aurones.Chlorophylls.y)
StateMats
ARDxy2 <- getFullMat(StateMats, RateClassMat)

pp.Aurones.Chlorophylls.ARD.1<-corHMM(tree,Aurones.Chlorophylls,rate.cat=1,node.states="marginal")
pp.Aurones.Chlorophylls.ARD.1
plotMKmodel(pp.Aurones.Chlorophylls.ARD.1)
pp.Aurones.Chlorophylls.ER.1<-corHMM(tree,Aurones.Chlorophylls,rate.cat=1, model = "ER", node.states="marginal")
pp.Aurones.Chlorophylls.ER.1
plotMKmodel(pp.Aurones.Chlorophylls.ER.1)
pp.Aurones.Chlorophylls.IND.1<-corHMM(tree,Aurones.Chlorophylls,rate.cat=1,rate.mat=Aurones.Chlorophylls.ind, node.states="marginal")
pp.Aurones.Chlorophylls.IND.1
plotMKmodel(pp.Aurones.Chlorophylls.IND.1)
pp.Aurones.Chlorophylls.ARDx.1<-corHMM(tree,Aurones.Chlorophylls,rate.cat=1,rate.mat=Aurones.Chlorophylls.x, node.states="marginal")
pp.Aurones.Chlorophylls.ARDx.1
plotMKmodel(pp.Aurones.Chlorophylls.ARDx.1)
pp.Aurones.Chlorophylls.ARDy.1<-corHMM(tree,Aurones.Chlorophylls,rate.cat=1,rate.mat=Aurones.Chlorophylls.y, node.states="marginal")
pp.Aurones.Chlorophylls.ARDy.1
plotMKmodel(pp.Aurones.Chlorophylls.ARDy.1)

pp.Aurones.Chlorophylls.ARD.2<-corHMM(tree,Aurones.Chlorophylls,rate.cat=2,node.states="marginal")
pp.Aurones.Chlorophylls.ARD.2
pp.Aurones.Chlorophylls.ER.2<-corHMM(tree,Aurones.Chlorophylls,rate.cat=2, model = "ER", node.states="marginal")
pp.Aurones.Chlorophylls.ER.2

pp.Aurones.Chlorophylls.IND.2<-corHMM(tree,Aurones.Chlorophylls,rate.cat=2,rate.mat=IND2, node.states="marginal")
pp.Aurones.Chlorophylls.IND.2

pp.Aurones.Chlorophylls.ARDx.2<-corHMM(tree,Aurones.Chlorophylls,rate.cat=2,rate.mat=ARDx2, node.states="marginal")
pp.Aurones.Chlorophylls.ARDx.2

pp.Aurones.Chlorophylls.ARDy.2<-corHMM(tree,Aurones.Chlorophylls,rate.cat=2,rate.mat=ARDy2, node.states="marginal")
pp.Aurones.Chlorophylls.ARDy.2

pp.Aurones.Chlorophylls.ARDxy.2<-corHMM(tree,Aurones.Chlorophylls,rate.cat=2,rate.mat=ARDxy2, node.states="marginal")
pp.Aurones.Chlorophylls.ARDxy.2

simmap.Aurones.Chlorophylls <- makeSimmap(tree=tree, data=Aurones.Chlorophylls, model=pp.Aurones.Chlorophylls.IND.2$solution, rate.cat=2, nSim=100, nCores=1)
simmap.Aurones.Chlorophylls <- summary(simmap.Aurones.Chlorophylls)
#only a little bit better the xy2 model than ind2
#simmap.Aurones.Chlorophylls2 <- makeSimmap(tree=tree, data=Aurones.Chlorophylls, #summary.simmap.Aurones.Chlorophylls2 <- summary(simmap.Aurones.Chlorophylls2)

pdffn = paste0("Model.Aurones.Chlorophylls2rates.IND.pdf")
pdf(file=pdffn, width=6, height=8)
plotMKmodel(pp.Aurones.Chlorophylls.IND.2)
dev.off()

pdffn = paste0("Model.Aurones.Chlorophylls2rates.ARDsy.pdf")
pdf(file=pdffn, width=6, height=8)
plotMKmodel(pp.Aurones.Chlorophylls.ARDxy.2)
dev.off()

pdffn = paste0("Aurones.Chlorophylls2rates.IND.pdf")
pdf(file=pdffn, width=6, height=60)
plotRECON(tree,pp.Aurones.Chlorophylls.IND.2$states,cex=0.5, pie.cex=0.5,title="Aurones.Chlorophylls 2 rates IND")
dev.off()




cols<-setNames(c("white","lightgrey","darkgrey", "black", "red","darkorange","orange", "yellow"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Aurones.Chlorophylls2ratesfanIND.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Aurones.Chlorophylls.IND.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","lightgrey","darkgrey", "black", "red","darkorange","orange", "yellow"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Aurones.Chlorophylls2ratesfanIND.color.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Aurones.Chlorophylls.IND.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","white","white", "white", "grey","grey","grey", "grey"),levels(c("(1,R1)", "(2,R1)", "(3,R1)", "(4,R1)", "(1,R2)", "(2,R2)", "(3,R2)", "(4,R2)")))
pdffn = paste0("Aurones.Chlorophylls2ratesfanIND.rates.pdf")
pdf(file=pdffn, width=27, height=27)
plot(tree,type="fan",cex=0.6,font=3,lwd=1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Aurones.Chlorophylls.IND.2$states,piecol=cols,cex=0.2)
dev.off()

cols<-setNames(c("white","red","lightgrey","darkorange","darkgrey", "orange","black", "yellow"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Aurones.Chlorophylls.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Aurones.Chlorophylls, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()


cols<-setNames(c("white","grey","white","grey","white","grey","white","grey"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Aurones.Chlorophylls.rates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Aurones.Chlorophylls, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

cols<-setNames(c("white","white","yellow","yellow","pink","pink", "red","red"),c("0_0,R1)","(0_0,R2)", "(0_1,R1)", "(0_1,R2)", "(1_0,R1)", "(1_0,R2)", "(1_1,R1)", "(1_1,R2)"))
pdffn = paste0("summary.simmap.Aurones.Chlorophylls.color.pdf")
pdf(file=pdffn, width=100, height=100)
plot(summary.simmap.Aurones.Chlorophylls, cex = 0.3, fsize=0.2, lwd = 0.8, type="fan", colors = cols)
dev.off()

```


Phylogenetic signal 
```{r}

library(geiger)

#Anthocyanins
vAnthocyanins <- mydata[,7]
names(vAnthocyanins) <- mydata[,12]
vAnthocyanins <- vAnthocyanins[!is.na(vAnthocyanins)]
vAnthocyanins <- vAnthocyanins[names(vAnthocyanins) != "Genista_monosperma"]
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,names(vAnthocyanins))
tree <- drop.tip(tree, tipstoremove)
vAnthocyanins[vAnthocyanins==0] <- 2
lambda.Anthocyanins <- fitDiscrete(tree, vAnthocyanins, model = "ER", transform = "lambda", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
lambda.Anthocyanins.bm <- fitDiscrete(tree, vAnthocyanins, model = "ER", transform = "none", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
tree.lambda <- rescale(tree, "lambda")
tree.lambda(0)
lambda.Anthocyanins.0 <- fitDiscrete(tree.lambda(0), vAnthocyanins, model = "ER", transform = "none", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
lambda.Anthocyanins
lambda.Anthocyanins.bm
lambda.Anthocyanins.0

#Aurones
vAurones <- mydata[,8]
names(vAurones) <- mydata[,12]
vAurones <- Aurones[!is.na(vAurones)]
vAurones <- vAurones[names(vAurones) != "Genista_monosperma"]
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,names(vAurones))
tree <- drop.tip(tree, tipstoremove)
vAurones[vAurones==0] <- 2
lambda.Aurones <- fitDiscrete(tree, vAurones, model = "ARD", transform = "lambda", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
lambda.Aurones.bm <- fitDiscrete(tree, vAurones, model = "ARD", transform = "none", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
tree.lambda <- rescale(tree, "lambda")
tree.lambda(0)
lambda.Aurones.0 <- fitDiscrete(tree.lambda(0), vAurones, model = "ARD", transform = "none", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
lambda.Aurones
lambda.Aurones.bm
lambda.Aurones.0

#Carotenoids
vCarotenoids <- mydata[,9]
names(vCarotenoids) <- mydata[,12]
vCarotenoids <- vCarotenoids[!is.na(vCarotenoids)]
vCarotenoids <- vCarotenoids[names(vCarotenoids) != "Genista_monosperma"]
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,names(vCarotenoids))
tree <- drop.tip(tree, tipstoremove)
vCarotenoids[vCarotenoids==0] <- 2
lambda.Carotenoids <- fitDiscrete(tree, vCarotenoids, model = "ARD", transform = "lambda", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
lambda.Carotenoids.bm <- fitDiscrete(tree, vCarotenoids, model = "ARD", transform = "none", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
tree.lambda <- rescale(tree, "lambda")
tree.lambda(0)
lambda.Carotenoids.0 <- fitDiscrete(tree.lambda(0), vCarotenoids, model = "ARD", transform = "none", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
lambda.Carotenoids
lambda.Carotenoids.bm
lambda.Carotenoids.0

#Chlorophylls
vChlorophylls <- mydata[,10]
names(vChlorophylls) <- mydata[,12]
vChlorophylls <- vChlorophylls[!is.na(vChlorophylls)]
vChlorophylls <- vChlorophylls[names(vChlorophylls) != "Genista_monosperma"]
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,names(vChlorophylls))
tree <- drop.tip(tree, tipstoremove)
vChlorophylls[vChlorophylls==0] <- 2
lambda.Chlorophylls <- fitDiscrete(tree, vChlorophylls, model = "ARD", transform = "lambda", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
lambda.Chlorophylls.bm <- fitDiscrete(tree, vChlorophylls, model = "ARD", transform = "none", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
tree.lambda <- rescale(tree, "lambda")
tree.lambda(0)
lambda.Chlorophylls.0 <- fitDiscrete(tree.lambda(0), vChlorophylls, model = "ARD", transform = "none", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
lambda.Chlorophylls
lambda.Chlorophylls.bm
lambda.Chlorophylls.0


#Npigments
ARDstep <- matrix(c(0, 1, 0, 0, 2, 0, 3, 0, 0, 4, 0, 5, 0, 0, 6, 0), 4)
vNpigments <- mydata[,11]
names(vNpigments) <- mydata[,12]
vNpigments <- vNpigments[!is.na(vNpigments)]
vNpigments <- vNpigments[names(vNpigments) != "Genista_monosperma"]
tree <- multi2di(mytree$scenario.2)
tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
tipstoremove <- setdiff(tree$tip.label,names(vNpigments))
tree <- drop.tip(tree, tipstoremove)
vNpigments[vNpigments==0] <- "zero"
vNpigments[vNpigments==1] <- "one"
vNpigments[vNpigments==2] <- "two"
vNpigments[vNpigments==3] <- "three"
vNpigments <- factor(vNpigments)
lambda.Npigments <- fitDiscrete(tree, vNpigments, model = ARDstep, transform = "lambda", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
lambda.Npigments.bm <- fitDiscrete(tree, vNpigments, model = ARDstep, transform = "none", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
tree.lambda <- rescale(tree, "lambda")
tree.lambda(0)
lambda.Npigments.0 <- fitDiscrete(tree.lambda(0), vNpigments, model = ARDstep, transform = "none", niter = 1000, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
lambda.Npigments
lambda.Npigments.bm
lambda.Npigments.0



```




ML reconstruction number of pigments.

```{r}
  library(phytools)
  
  names(mydata)
  vvNPigments <- mydata[,11]
  names(vvNPigments) <- mydata[,12]
  tree <- multi2di(mytree$scenario.2)
  tree$edge.length[tree$edge.length==0]<-max(nodeHeights(tree))*1e-6
  
  vvNPigments<-vvNPigments[!is.na(vvNPigments)]
  tipstoremove <- setdiff(tree$tip.label,names(NPigments))
  tree <- drop.tip(tree, tipstoremove)
  
  
names(mydata)
vvFlavonoids <- mydata[,7]
names(vvFlavonoids) <- mydata[,12]
vvFlavonoids[vvFlavonoids==0] <- 1
vvFlavonoids
vvAnthocyanins <- mydata[,7]
names(vvAnthocyanins) <- mydata[,12]
vvAnthocyanins[vvAnthocyanins==0] <- 2
vvAnthocyanins
vvAurones <- mydata[,8]
names(vvAurones) <- mydata[,12]
vvAurones[vvAurones==0] <- 2
vvAurones
vvCarotenoids <- mydata[,9]
names(vvCarotenoids) <- mydata[,12]
vvCarotenoids[vvCarotenoids==0] <- 2
vvCarotenoids
vvChlorophylls <- mydata[,10]
names(vvChlorophylls) <- mydata[,12]
vvChlorophylls[vvChlorophylls==0] <- 2
vvChlorophylls

#cols<-setNames(c("lightpink","#e75480","purple","#301934"),levels(as.factor(vvNPigments)))
cols<-setNames(c("white","lightgrey","#555555","black"),levels(as.factor(vvNPigments)))
cols5<-setNames(c("lightyellow","lightgrey"),levels(as.factor(vvFlavonoids)))
cols2<-setNames(c("blue","lightgrey"),levels(as.factor(vvAnthocyanins)))
cols3<-setNames(c("orange","lightgrey"),levels(as.factor(vvCarotenoids)))
cols4<-setNames(c("#FFCC00","lightgrey"),levels(as.factor(vvAurones)))
cols6<-setNames(c("darkgreen","lightgrey"),levels(as.factor(vvChlorophylls)))
#node1 <- getMRCA(tree, c("Acritopappus_sp","Richterago_arenaria"))
node2 <- getMRCA(tree, c("Orchis_anthropophora","Gomesa_hydrophila"))
node3 <- getMRCA(tree, c("Clinopodium_nepeta","Stachys_ocymastrum"))
#node4 <- getMRCA(tree, c("Pedicularis_sylvatica","Cistanche_phelypaea"))
#node5 <- getMRCA(tree, c("Silene_adscendens","Paronychia_argentea"))
node6 <- getMRCA(tree, c("Solanum_paniculatum","Evolvulus_lithospermoides"))
#node7<- getMRCA(tree, c("Trifolium_fragiferum","Hymenaea_sp"))
node8<- getMRCA(tree, c("Heliotropium_europaeum","Cynoglossum_clandestinum"))
#node9<- getMRCA(tree, c("Sisymbrium_austriacum","Malcolmia_littorea"))
node10<- getMRCA(tree, c("Cistus_crispus","Malva_maroccana"))
node11<- getMRCA(tree, c("Nigella_damascena","Papaver_argemone"))
node12<- getMRCA(tree, c("Linum_trigynum","Euphorbia_segetalis"))
node13<- getMRCA(tree, c("Rosa_canina","Crataegus_monogyna"))
node14<- getMRCA(tree, c("Banisteriopsis_campestris","Byrsonima_dealbata"))
node15<- getMRCA(tree, c("Geranium_molle","Erodium_moschatum"))
node16<- getMRCA(tree, c("Cambessedesia_corymbosa","Miconia_rubiginosa"))
node17<- getMRCA(tree, c("Declieuxia_fruticosa","Asperula_hirsuta"))
node18<- getMRCA(tree, c("Cymbalaria_muralis","Linaria_spartea"))
#node19<- getMRCA(tree, c("Romulea_bulbocodium","Iris_planifolia"))
node20<- getMRCA(tree, c("Allium_roseum","Acis_autumnalis"))
#node21<- getMRCA(tree, c("Scilla_peruviana","Prospero_autumnale"))
node22<- getMRCA(tree, c("Xyris_asperula","Xyris_piranii"))

pdffn = paste0("ML_ARDstep2_NPigments.pdf")
pdf(file=pdffn, width=30, height=30)
par(mar = c(0.1, 0.1, 0.1, 0.1))
plot(tree,type="fan",show.tip.label = T, cex = 0.1,  tip.color="white", edge.color = "grey", edge.width = 5, no.margin = F)
tiplabels(pie=to.matrix(vvNPigments[tree$tip.label],
    levels(as.factor(vvNPigments))),piecol=cols, bg=cols,cex=0.1,offset = 1)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=pp.Npigments.ARD.2$states,piecol=cols,cex=0.2)
add.simmap.legend(colors=cols,prompt=FALSE,x=1*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
tiplabels(pie=to.matrix(vvFlavonoids[tree$tip.label],
    levels(as.factor(vvFlavonoids))),piecol=cols5, bg=cols5,cex=0.1, offset = 2.5)
add.simmap.legend(colors=cols5,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
tiplabels(pie=to.matrix(vvAnthocyanins[tree$tip.label],
    levels(as.factor(vvAnthocyanins))),piecol=cols2, bg=cols2,cex=0.1, offset = 4)
add.simmap.legend(colors=cols2,prompt=FALSE,x=0.8*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
tiplabels(pie=to.matrix(vvCarotenoids[tree$tip.label],
    levels(as.factor(vvCarotenoids))),piecol=cols3, bg=cols3,cex=0.1, offset = 5.5)
add.simmap.legend(colors=cols3,prompt=FALSE,x=0.7*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
tiplabels(pie=to.matrix(vvChlorophylls[tree$tip.label],
    levels(as.factor(vvChlorophylls))),piecol=cols6, bg=cols6,cex=0.1, offset = 7)
add.simmap.legend(colors=cols6,prompt=FALSE,x=0.8*par()$usr[1],
    y=0.9*par()$usr[3],fsize=2)
tiplabels(pie=to.matrix(vvAurones[tree$tip.label],
    levels(as.factor(vvAurones))),piecol=cols4, bg=cols4,cex=0.1, offset = 8.5)
add.simmap.legend(colors=cols4,prompt=FALSE,x=0.7*par()$usr[1],
    y=0.9*par()$usr[3],fsize=2)
#arc.cladelabels(tree, "Asteraceae", node1, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=2,orientation="curved", stretch=1)
arc.cladelabels(tree, "Orchidaceae", node2, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=2,orientation="curved", stretch=1)
arc.cladelabels(tree, "Lamiaceae", node3, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=2,orientation="curved", stretch=1)
#arc.cladelabels(tree, "Orobanchaceae", node4, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=1.5,orientation="curved", stretch=1)
#arc.cladelabels(tree, "Caryophyllaceae", node5, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=2,orientation="curved", stretch=1)
arc.cladelabels(tree, "Solanaceae-Convolvulaceae", node6, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=1.5,orientation="curved", stretch=1)
#arc.cladelabels(tree, "Fabaceae", node7, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=2,orientation="curved", stretch=1)
arc.cladelabels(tree, "Boraginaceae", node8, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=1.5,orientation="curved", stretch=1)
#arc.cladelabels(tree, "Brassicaceae", node9, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=1.5,orientation="curved", stretch=1)
arc.cladelabels(tree, "Malvaceae-Cistaceae", node10, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=2,orientation="curved", stretch=1)
arc.cladelabels(tree, "Papaveraceae-Ranunculaceae", node11, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=2,orientation="curved", stretch=1)
arc.cladelabels(tree, "Linaceae-Euphorbiaceae", node12, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=1,orientation="curved", stretch=1)
arc.cladelabels(tree, "Rosaceae", node13, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=1.5,orientation="curved", stretch=1)
arc.cladelabels(tree, "Malpighiaceae", node14, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=1.5,orientation="curved", stretch=1)
arc.cladelabels(tree, "Geraniaceae", node15, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=1.5,orientation="curved", stretch=1)
arc.cladelabels(tree, "Melastomataceae", node16, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=2,orientation="curved", stretch=1)
arc.cladelabels(tree, "Rubiaceae", node17, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=1.5,orientation="curved", stretch=1)
arc.cladelabels(tree, "Plantaginaceae", node18, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=1.5,orientation="curved", stretch=1)
#arc.cladelabels(tree, "Iridaceae", node19, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=2,orientation="curved", stretch=1)
arc.cladelabels(tree, "Amaryllidaceae", node20, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=1.8,orientation="curved", stretch=1)
#arc.cladelabels(tree, "Asparagaceae", node21, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=1.5,orientation="curved", stretch=1)
arc.cladelabels(tree, "Xyridaceae", node22, ln.offset=1.1, lab.offset=1.12,mark.node=FALSE, cex=1.5,orientation="curved", stretch=1)
dev.off()

```


